BEGIN;

DROP TYPE IF EXISTS user_role CASCADE;

DROP TYPE IF EXISTS transfer_type CASCADE;

DROP FUNCTION IF EXISTS is_valid_pesel CASCADE;

DROP TABLE IF EXISTS towns CASCADE;

DROP TABLE IF EXISTS postal_codes CASCADE;

DROP TABLE IF EXISTS postal_codes_towns CASCADE;

DROP TABLE IF EXISTS accounts CASCADE;

DROP TABLE IF EXISTS accounts_info CASCADE;

DROP TABLE IF EXISTS wallets CASCADE;

DROP TABLE IF EXISTS companies CASCADE;

DROP TABLE IF EXISTS companies_info CASCADE;

DROP TABLE IF EXISTS ipo CASCADE;

DROP TABLE IF EXISTS companies_status CASCADE;

DROP TABLE IF EXISTS external_transfers CASCADE;

DROP FUNCTION IF EXISTS check_order_type CASCADE;

DROP TABLE IF EXISTS order_types CASCADE;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS order_cancellations CASCADE;

DROP TABLE IF EXISTS transactions CASCADE;

DROP TABLE IF EXISTS subscriptions CASCADE;

COMMIT;